# Copyright (C) 2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/prague/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/huawei/prague/proprietary/vendor/etc/libnfc-brcm.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-brcm.conf \
    vendor/huawei/prague/proprietary/vendor/etc/libnfc-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp.conf \
    vendor/huawei/prague/proprietary/vendor/etc/cfg_prague_al00_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_prague_al00_hisi.ini \
    vendor/huawei/prague/proprietary/vendor/etc/cfg_prague_l21_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_prague_l21_hisi.ini \
    vendor/huawei/prague/proprietary/vendor/etc/cfg_prague_l22_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_prague_l22_hisi.ini \
    vendor/huawei/prague/proprietary/vendor/etc/cfg_prague_l23_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_prague_l23_hisi.ini \
    vendor/huawei/prague/proprietary/vendor/etc/cfg_prague_l31_LVSAW_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_prague_l31_LVSAW_hisi.ini \
    vendor/huawei/prague/proprietary/vendor/etc/cfg_prague_l31_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_prague_l31_hisi.ini \
    vendor/huawei/prague/proprietary/vendor/etc/cfg_prague_l62_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_prague_l62_hisi.ini \
    vendor/huawei/prague/proprietary/vendor/etc/cfg_prague_tl00_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_prague_tl00_hisi.ini \
    vendor/huawei/prague/proprietary/vendor/etc/cfg_prague_tl10_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_prague_tl10_hisi.ini
